/**
 * Roblox Lua Script Exporter
 *
 * Exports stories to Roblox Lua ModuleScripts for dialogue systems,
 * quest systems, and interactive narratives.
 */

import type { Story } from '../models/Story';
import type { Passage } from '../models/Passage';
import JSZip from 'jszip';

export interface RobloxExportOptions {
  projectName: string;
  description: string;
  includeGUI: boolean;
  includeDialogueSystem: boolean;
  includeBadges: boolean;
  includeDataStore: boolean;
}

export class RobloxExporter {
  /**
   * Export story to Roblox Lua scripts
   */
  static async export(story: Story, options: RobloxExportOptions): Promise<Blob> {
    const zip = new JSZip();

    const projectName = this.sanitizeName(options.projectName || story.metadata.title);

    // Create main story module
    const storyModule = this.generateStoryModule(story);
    zip.file(`${projectName}StoryModule.lua`, storyModule);

    // Create dialogue system if requested
    if (options.includeDialogueSystem) {
      const dialogueSystem = this.generateDialogueSystem(story);
      zip.file(`${projectName}DialogueSystem.lua`, dialogueSystem);
    }

    // Create GUI system if requested
    if (options.includeGUI) {
      const guiScript = this.generateGUIScript(story);
      zip.file(`${projectName}GUI.lua`, guiScript);
    }

    // Create badge system if requested
    if (options.includeBadges) {
      const badgeScript = this.generateBadgeScript(story);
      zip.file(`${projectName}Badges.lua`, badgeScript);
    }

    // Create data store script if requested
    if (options.includeDataStore) {
      const dataStoreScript = this.generateDataStoreScript(story);
      zip.file(`${projectName}DataStore.lua`, dataStoreScript);
    }

    // Create initialization script
    const initScript = this.generateInitScript(story, options);
    zip.file(`${projectName}Init.lua`, initScript);

    // Create README
    const readme = this.generateReadme(story, options);
    zip.file('README.txt', readme);

    // Generate the ZIP file
    const blob = await zip.generateAsync({ type: 'blob' });
    return blob;
  }

  /**
   * Sanitize name for Roblox (no special characters)
   */
  private static sanitizeName(name: string): string {
    return name
      .replace(/[^a-zA-Z0-9_]/g, '_')
      .replace(/_+/g, '_')
      .replace(/^_|_$/g, '');
  }

  /**
   * Generate main story module with all passages and choices
   */
  private static generateStoryModule(story: Story): string {
    const lines: string[] = [];

    lines.push(`-- ${story.metadata.title} Story Module`);
    lines.push(`-- Generated by Whisker Editor - Kids Mode`);
    lines.push(`-- Author: ${story.metadata.author}`);
    lines.push('');
    lines.push('local StoryModule = {}');
    lines.push('');
    lines.push('-- Story Data');
    lines.push('StoryModule.Title = "' + this.escapeString(story.metadata.title) + '"');
    lines.push('StoryModule.Author = "' + this.escapeString(story.metadata.author) + '"');
    lines.push('StoryModule.Version = "' + (story.metadata.version || '1.0.0') + '"');
    lines.push('');

    // Generate passages table
    lines.push('-- Passages');
    lines.push('StoryModule.Passages = {');

    for (const passage of story.passages.values()) {
      lines.push(`  ["${this.escapeString(passage.id)}"] = {`);
      lines.push(`    Id = "${this.escapeString(passage.id)}",`);
      lines.push(`    Title = "${this.escapeString(passage.title)}",`);
      lines.push(`    Content = [[${this.escapeString(passage.content)}]],`);

      // Add choices
      if (passage.choices && passage.choices.length > 0) {
        lines.push('    Choices = {');
        passage.choices.forEach((choice, index) => {
          lines.push('      {');
          lines.push(`        Text = "${this.escapeString(choice.text)}",`);
          lines.push(`        Target = "${this.escapeString(choice.target)}",`);
          if (choice.condition) {
            lines.push(`        Condition = "${this.escapeString(choice.condition)}",`);
          }
          lines.push(`      },`);
        });
        lines.push('    },');
      } else {
        lines.push('    Choices = {},');
      }

      // Add tags
      if (passage.tags && passage.tags.length > 0) {
        lines.push(`    Tags = {${passage.tags.map(t => `"${this.escapeString(t)}"`).join(', ')}},`);
      }

      lines.push('  },');
    }

    lines.push('}');
    lines.push('');

    // Add start passage
    lines.push(`StoryModule.StartPassage = "${this.escapeString(story.startPassage)}"`);
    lines.push('');

    // Helper functions
    lines.push('-- Get passage by ID');
    lines.push('function StoryModule:GetPassage(passageId)');
    lines.push('  return self.Passages[passageId]');
    lines.push('end');
    lines.push('');

    lines.push('-- Check if passage is an ending (no choices)');
    lines.push('function StoryModule:IsEnding(passageId)');
    lines.push('  local passage = self:GetPassage(passageId)');
    lines.push('  return passage and #passage.Choices == 0');
    lines.push('end');
    lines.push('');

    lines.push('return StoryModule');

    return lines.join('\n');
  }

  /**
   * Generate dialogue system script
   */
  private static generateDialogueSystem(story: Story): string {
    const lines: string[] = [];

    lines.push('-- Dialogue System for ' + story.metadata.title);
    lines.push('-- Handles displaying passages and managing player choices');
    lines.push('');
    lines.push('local DialogueSystem = {}');
    lines.push('local StoryModule = require(script.Parent:WaitForChild("' + this.sanitizeName(story.metadata.title) + 'StoryModule"))');
    lines.push('');
    lines.push('-- Current passage for each player');
    lines.push('local playerPassages = {}');
    lines.push('');

    lines.push('-- Show passage to player');
    lines.push('function DialogueSystem:ShowPassage(player, passageId)');
    lines.push('  local passage = StoryModule:GetPassage(passageId)');
    lines.push('  if not passage then');
    lines.push('    warn("Passage not found: " .. passageId)');
    lines.push('    return');
    lines.push('  end');
    lines.push('');
    lines.push('  -- Store current passage');
    lines.push('  playerPassages[player.UserId] = passageId');
    lines.push('');
    lines.push('  -- Fire to client to display');
    lines.push('  local event = game.ReplicatedStorage:FindFirstChild("ShowDialogue")');
    lines.push('  if event then');
    lines.push('    event:FireClient(player, passage)');
    lines.push('  end');
    lines.push('end');
    lines.push('');

    lines.push('-- Handle player choice');
    lines.push('function DialogueSystem:HandleChoice(player, choiceIndex)');
    lines.push('  local currentPassageId = playerPassages[player.UserId]');
    lines.push('  if not currentPassageId then return end');
    lines.push('');
    lines.push('  local passage = StoryModule:GetPassage(currentPassageId)');
    lines.push('  if not passage then return end');
    lines.push('');
    lines.push('  local choice = passage.Choices[choiceIndex]');
    lines.push('  if not choice then return end');
    lines.push('');
    lines.push('  -- Show next passage');
    lines.push('  self:ShowPassage(player, choice.Target)');
    lines.push('end');
    lines.push('');

    lines.push('-- Start story for player');
    lines.push('function DialogueSystem:StartStory(player)');
    lines.push('  self:ShowPassage(player, StoryModule.StartPassage)');
    lines.push('end');
    lines.push('');

    lines.push('-- Initialize');
    lines.push('function DialogueSystem:Init()');
    lines.push('  -- Create remote events if they don\'t exist');
    lines.push('  if not game.ReplicatedStorage:FindFirstChild("ShowDialogue") then');
    lines.push('    local event = Instance.new("RemoteEvent")');
    lines.push('    event.Name = "ShowDialogue"');
    lines.push('    event.Parent = game.ReplicatedStorage');
    lines.push('  end');
    lines.push('');
    lines.push('  if not game.ReplicatedStorage:FindFirstChild("ChoiceSelected") then');
    lines.push('    local event = Instance.new("RemoteEvent")');
    lines.push('    event.Name = "ChoiceSelected"');
    lines.push('    event.Parent = game.ReplicatedStorage');
    lines.push('  end');
    lines.push('');
    lines.push('  -- Connect choice handler');
    lines.push('  game.ReplicatedStorage.ChoiceSelected.OnServerEvent:Connect(function(player, choiceIndex)');
    lines.push('    self:HandleChoice(player, choiceIndex)');
    lines.push('  end)');
    lines.push('end');
    lines.push('');

    lines.push('return DialogueSystem');

    return lines.join('\n');
  }

  /**
   * Generate GUI script for client-side display
   */
  private static generateGUIScript(story: Story): string {
    const lines: string[] = [];

    lines.push('-- GUI Script for ' + story.metadata.title);
    lines.push('-- Client-side script to display dialogue in ScreenGui');
    lines.push('');
    lines.push('local Players = game:GetService("Players")');
    lines.push('local ReplicatedStorage = game:GetService("ReplicatedStorage")');
    lines.push('');
    lines.push('local player = Players.LocalPlayer');
    lines.push('local playerGui = player:WaitForChild("PlayerGui")');
    lines.push('');
    lines.push('-- Create main GUI');
    lines.push('local screenGui = Instance.new("ScreenGui")');
    lines.push('screenGui.Name = "StoryGUI"');
    lines.push('screenGui.ResetOnSpawn = false');
    lines.push('screenGui.Parent = playerGui');
    lines.push('');
    lines.push('-- Create dialogue frame');
    lines.push('local frame = Instance.new("Frame")');
    lines.push('frame.Name = "DialogueFrame"');
    lines.push('frame.Size = UDim2.new(0.6, 0, 0.4, 0)');
    lines.push('frame.Position = UDim2.new(0.2, 0, 0.5, 0)');
    lines.push('frame.BackgroundColor3 = Color3.fromRGB(30, 30, 30)');
    lines.push('frame.BorderSizePixel = 0');
    lines.push('frame.Visible = false');
    lines.push('frame.Parent = screenGui');
    lines.push('');
    lines.push('-- Add UICorner');
    lines.push('local corner = Instance.new("UICorner")');
    lines.push('corner.CornerRadius = UDim.new(0, 12)');
    lines.push('corner.Parent = frame');
    lines.push('');
    lines.push('-- Title label');
    lines.push('local titleLabel = Instance.new("TextLabel")');
    lines.push('titleLabel.Size = UDim2.new(1, -20, 0, 40)');
    lines.push('titleLabel.Position = UDim2.new(0, 10, 0, 10)');
    lines.push('titleLabel.BackgroundTransparency = 1');
    lines.push('titleLabel.TextColor3 = Color3.fromRGB(255, 255, 255)');
    lines.push('titleLabel.TextScaled = true');
    lines.push('titleLabel.Font = Enum.Font.GothamBold');
    lines.push('titleLabel.Parent = frame');
    lines.push('');
    lines.push('-- Content label');
    lines.push('local contentLabel = Instance.new("TextLabel")');
    lines.push('contentLabel.Size = UDim2.new(1, -20, 0.4, -60)');
    lines.push('contentLabel.Position = UDim2.new(0, 10, 0, 60)');
    lines.push('contentLabel.BackgroundTransparency = 1');
    lines.push('contentLabel.TextColor3 = Color3.fromRGB(220, 220, 220)');
    lines.push('contentLabel.TextScaled = true');
    lines.push('contentLabel.Font = Enum.Font.Gotham');
    lines.push('contentLabel.TextWrapped = true');
    lines.push('contentLabel.TextXAlignment = Enum.TextXAlignment.Left');
    lines.push('contentLabel.TextYAlignment = Enum.TextYAlignment.Top');
    lines.push('contentLabel.Parent = frame');
    lines.push('');
    lines.push('-- Choices container');
    lines.push('local choicesFrame = Instance.new("Frame")');
    lines.push('choicesFrame.Size = UDim2.new(1, -20, 0.4, 0)');
    lines.push('choicesFrame.Position = UDim2.new(0, 10, 0.6, 0)');
    lines.push('choicesFrame.BackgroundTransparency = 1');
    lines.push('choicesFrame.Parent = frame');
    lines.push('');
    lines.push('-- Function to create choice button');
    lines.push('local function createChoiceButton(text, index, total)');
    lines.push('  local button = Instance.new("TextButton")');
    lines.push('  button.Size = UDim2.new(1, 0, 1 / total, -5)');
    lines.push('  button.Position = UDim2.new(0, 0, (index - 1) / total, 0)');
    lines.push('  button.BackgroundColor3 = Color3.fromRGB(50, 130, 200)');
    lines.push('  button.TextColor3 = Color3.fromRGB(255, 255, 255)');
    lines.push('  button.Text = text');
    lines.push('  button.TextScaled = true');
    lines.push('  button.Font = Enum.Font.GothamBold');
    lines.push('');
    lines.push('  local btnCorner = Instance.new("UICorner")');
    lines.push('  btnCorner.CornerRadius = UDim.new(0, 8)');
    lines.push('  btnCorner.Parent = button');
    lines.push('');
    lines.push('  button.MouseButton1Click:Connect(function()');
    lines.push('    ReplicatedStorage:WaitForChild("ChoiceSelected"):FireServer(index)');
    lines.push('  end)');
    lines.push('');
    lines.push('  return button');
    lines.push('end');
    lines.push('');
    lines.push('-- Handle showing dialogue');
    lines.push('ReplicatedStorage:WaitForChild("ShowDialogue").OnClientEvent:Connect(function(passage)');
    lines.push('  -- Clear previous choices');
    lines.push('  for _, child in pairs(choicesFrame:GetChildren()) do');
    lines.push('    child:Destroy()');
    lines.push('  end');
    lines.push('');
    lines.push('  -- Set content');
    lines.push('  titleLabel.Text = passage.Title');
    lines.push('  contentLabel.Text = passage.Content');
    lines.push('');
    lines.push('  -- Create choice buttons');
    lines.push('  local choiceCount = #passage.Choices');
    lines.push('  if choiceCount > 0 then');
    lines.push('    for i, choice in ipairs(passage.Choices) do');
    lines.push('      local button = createChoiceButton(choice.Text, i, choiceCount)');
    lines.push('      button.Parent = choicesFrame');
    lines.push('    end');
    lines.push('  end');
    lines.push('');
    lines.push('  -- Show frame');
    lines.push('  frame.Visible = true');
    lines.push('end)');

    return lines.join('\n');
  }

  /**
   * Generate badge system script
   */
  private static generateBadgeScript(story: Story): string {
    const lines: string[] = [];

    lines.push('-- Badge System for ' + story.metadata.title);
    lines.push('');
    lines.push('local BadgeService = game:GetService("BadgeService")');
    lines.push('local Players = game:GetService("Players")');
    lines.push('');
    lines.push('local BadgeSystem = {}');
    lines.push('');
    lines.push('-- Badge IDs (replace with your actual badge IDs from Roblox)');
    lines.push('BadgeSystem.Badges = {');
    lines.push('  StoryComplete = 0, -- Replace with your badge ID');
    lines.push('  FirstChoice = 0, -- Replace with your badge ID');
    lines.push('  AllEndings = 0, -- Replace with your badge ID');
    lines.push('}');
    lines.push('');
    lines.push('-- Award badge to player');
    lines.push('function BadgeSystem:AwardBadge(player, badgeId)');
    lines.push('  if badgeId == 0 then');
    lines.push('    return -- Badge ID not set');
    lines.push('  end');
    lines.push('');
    lines.push('  local success, hasBadge = pcall(function()');
    lines.push('    return BadgeService:UserHasBadgeAsync(player.UserId, badgeId)');
    lines.push('  end)');
    lines.push('');
    lines.push('  if success and not hasBadge then');
    lines.push('    local awarded = pcall(function()');
    lines.push('      BadgeService:AwardBadge(player.UserId, badgeId)');
    lines.push('    end)');
    lines.push('');
    lines.push('    if awarded then');
    lines.push('      print("Badge awarded to " .. player.Name)');
    lines.push('    end');
    lines.push('  end');
    lines.push('end');
    lines.push('');
    lines.push('return BadgeSystem');

    return lines.join('\n');
  }

  /**
   * Generate DataStore script for saving progress
   */
  private static generateDataStoreScript(story: Story): string {
    const lines: string[] = [];

    lines.push('-- DataStore for ' + story.metadata.title);
    lines.push('');
    lines.push('local DataStoreService = game:GetService("DataStoreService")');
    lines.push('local Players = game:GetService("Players")');
    lines.push('');
    lines.push('local storyDataStore = DataStoreService:GetDataStore("StoryProgress")');
    lines.push('');
    lines.push('local DataStore = {}');
    lines.push('');
    lines.push('-- Save player progress');
    lines.push('function DataStore:SaveProgress(player, passageId)');
    lines.push('  local success, err = pcall(function()');
    lines.push('    storyDataStore:SetAsync("Player_" .. player.UserId, {');
    lines.push('      CurrentPassage = passageId,');
    lines.push('      LastPlayed = os.time(),');
    lines.push('    })');
    lines.push('  end)');
    lines.push('');
    lines.push('  if not success then');
    lines.push('    warn("Failed to save progress:", err)');
    lines.push('  end');
    lines.push('end');
    lines.push('');
    lines.push('-- Load player progress');
    lines.push('function DataStore:LoadProgress(player)');
    lines.push('  local success, data = pcall(function()');
    lines.push('    return storyDataStore:GetAsync("Player_" .. player.UserId)');
    lines.push('  end)');
    lines.push('');
    lines.push('  if success and data then');
    lines.push('    return data');
    lines.push('  end');
    lines.push('');
    lines.push('  return nil');
    lines.push('end');
    lines.push('');
    lines.push('return DataStore');

    return lines.join('\n');
  }

  /**
   * Generate initialization script
   */
  private static generateInitScript(story: Story, options: RobloxExportOptions): string {
    const projectName = this.sanitizeName(options.projectName || story.metadata.title);
    const lines: string[] = [];

    lines.push('-- Initialization Script for ' + story.metadata.title);
    lines.push('-- Place this in ServerScriptService');
    lines.push('');
    lines.push('local StoryModule = require(script.Parent:WaitForChild("' + projectName + 'StoryModule"))');

    if (options.includeDialogueSystem) {
      lines.push('local DialogueSystem = require(script.Parent:WaitForChild("' + projectName + 'DialogueSystem"))');
    }

    lines.push('');
    lines.push('print("Loading story: " .. StoryModule.Title)');
    lines.push('');

    if (options.includeDialogueSystem) {
      lines.push('-- Initialize dialogue system');
      lines.push('DialogueSystem:Init()');
      lines.push('');
      lines.push('-- Auto-start story for players');
      lines.push('game.Players.PlayerAdded:Connect(function(player)');
      lines.push('  wait(2) -- Give time for character to load');
      lines.push('  DialogueSystem:StartStory(player)');
      lines.push('end)');
    }

    return lines.join('\n');
  }

  /**
   * Escape string for Lua
   */
  private static escapeString(str: string): string {
    return str
      .replace(/\\/g, '\\\\')
      .replace(/"/g, '\\"')
      .replace(/\n/g, '\\n')
      .replace(/\r/g, '')
      .replace(/\t/g, '    ');
  }

  /**
   * Generate README file
   */
  private static generateReadme(story: Story, options: RobloxExportOptions): string {
    const titleLine = story.metadata.title + ' - Roblox Story Scripts';
    const underline = '='.repeat(titleLine.length);
    const parts = [
      titleLine,
      underline,
      '',
      'A Roblox story experience created with Whisker Editor - Kids Mode.',
      '',
      'Author: ' + story.metadata.author,
      'Version: ' + (story.metadata.version || '1.0.0'),
      '',
      'INSTALLATION:',
      '-------------',
      '1. Open Roblox Studio',
      '2. Open your game/place',
      '3. In the Explorer window, find "ServerScriptService"',
      '4. Extract all .lua files from this ZIP',
      '5. Right-click ServerScriptService → Insert from File',
      '6. Select the Init script and all module scripts',
      '7. Make sure the GUI script goes into StarterPlayer → StarterPlayerScripts',
      '8. Test your game!',
      '',
      'SCRIPTS INCLUDED:',
      '-----------------',
    ];

    if (options.includeDialogueSystem) parts.push('✓ Dialogue System - Manages story flow');
    if (options.includeGUI) parts.push('✓ GUI Script - Displays dialogue to players');
    if (options.includeBadges) parts.push('✓ Badge System - Awards badges for achievements');
    if (options.includeDataStore) parts.push('✓ DataStore - Saves player progress');

    parts.push(
      '',
      'CUSTOMIZATION:',
      '--------------',
      '- Edit the GUI script to change colors, sizes, and positions',
      '- Modify the dialogue system to add custom logic',
      '- Add your own badge IDs in the badge system',
      '- Extend the DataStore to save more data',
      '',
      'TROUBLESHOOTING:',
      '----------------',
      '- Make sure all scripts are in the correct locations',
      '- Check the Output window for error messages',
      '- Ensure RemoteEvents are created in ReplicatedStorage',
      '- Test in Play mode, not just Run mode',
      '',
      'Created with Whisker Editor - Kids Mode',
      'https://github.com/writewhisker/whisker-editor-web',
      '',
      'Enjoy creating stories!'
    );

    return parts.join('\n');
  }

  /**
   * Get suggested filename for the export
   */
  static getSuggestedFilename(story: Story): string {
    return this.sanitizeName(story.metadata.title).toLowerCase() + '_roblox.zip';
  }
}
