<script lang="ts">
  import {
    saveSystemStore,
    storageType,
    slots,
    metadata,
    persistAll,
    type SaveStorageType,
    type SaveSlotType,
  } from '../stores/saveSystemStore';
  import { currentStory } from '../stores/storyStateStore';

  let viewMode: 'config' | 'variables' | 'code' = $state('config');
  let generatedCode = $state<any>(null);
  let selectedVariables = $state<string[]>([]);
  let excludedVariables = $state<string[]>([]);
  let customFieldKey = $state('');
  let customFieldLabel = $state('');
  let customFieldType: 'string' | 'number' | 'boolean' = $state('string');
  let copiedSection: string | null = $state(null);

  // Generate code when requested
  function generate() {
    if (!$currentStory) return;
    generatedCode = saveSystemStore.generateCode($currentStory);
    viewMode = 'code';
  }

  // Copy code to clipboard
  async function copyCode(section: string, code: string) {
    try {
      await navigator.clipboard.writeText(code);
      copiedSection = section;
      setTimeout(() => copiedSection = null, 2000);
    } catch (err) {
      console.error('Failed to copy:', err);
    }
  }

  // Download all code as a single file
  function downloadCode() {
    if (!generatedCode || !$currentStory) return;

    const code = `
// Save System for "${$currentStory.metadata.title}"
// Generated by Whisker Visual Editor

${generatedCode.types}

${generatedCode.saveFunction}

${generatedCode.loadFunction}

${generatedCode.deleteFunction}

${generatedCode.listFunction}

${generatedCode.utilities}
`.trim();

    const blob = new Blob([code], { type: 'text/typescript' });
    const url = URL.createObjectURL(blob);
    const a = document.createElement('a');
    a.href = url;
    a.download = 'saveSystem.ts';
    a.click();
    URL.revokeObjectURL(url);
  }

  // Add custom field
  function addCustomField() {
    if (!customFieldKey || !customFieldLabel) return;
    saveSystemStore.addCustomField(customFieldKey, customFieldLabel, customFieldType);
    customFieldKey = '';
    customFieldLabel = '';
    customFieldType = 'string';
  }

  // Update persist variables
  $effect(() => {
    if ($persistAll) {
      saveSystemStore.setExcludeVariables(excludedVariables);
    } else {
      saveSystemStore.setPersistVariables(selectedVariables);
    }
  });
</script>

<div class="h-full flex flex-col bg-white dark:bg-gray-800 border-l border-gray-200 dark:border-gray-700">
  <!-- Header -->
  <div class="p-4 border-b border-gray-200 dark:border-gray-700">
    <div class="flex items-center justify-between mb-2">
      <h2 class="text-lg font-semibold text-gray-900 dark:text-gray-100">
        💾 Save System Generator
      </h2>
      <button
        onclick={generate}
        disabled={!$currentStory}
        class="px-3 py-1 bg-blue-600 hover:bg-blue-700 disabled:bg-gray-400 text-white rounded text-sm font-medium transition-colors"
      >
        Generate Code
      </button>
    </div>

    {#if $currentStory}
      <div class="flex gap-2">
        <button
          onclick={() => viewMode = 'config'}
          class="px-2 py-1 text-xs rounded {viewMode === 'config' ? 'bg-blue-100 dark:bg-blue-900 text-blue-700 dark:text-blue-300' : 'bg-gray-100 dark:bg-gray-700 text-gray-600 dark:text-gray-300'}"
        >
          Configuration
        </button>
        <button
          onclick={() => viewMode = 'variables'}
          class="px-2 py-1 text-xs rounded {viewMode === 'variables' ? 'bg-blue-100 dark:bg-blue-900 text-blue-700 dark:text-blue-300' : 'bg-gray-100 dark:bg-gray-700 text-gray-600 dark:text-gray-300'}"
        >
          Variables
        </button>
        {#if generatedCode}
          <button
            onclick={() => viewMode = 'code'}
            class="px-2 py-1 text-xs rounded {viewMode === 'code' ? 'bg-blue-100 dark:bg-blue-900 text-blue-700 dark:text-blue-300' : 'bg-gray-100 dark:bg-gray-700 text-gray-600 dark:text-gray-300'}"
          >
            Generated Code
          </button>
        {/if}
      </div>
    {/if}
  </div>

  <!-- Content -->
  <div class="flex-1 overflow-y-auto p-4 space-y-4">
    {#if !$currentStory}
      <div class="text-center py-8 text-gray-500 dark:text-gray-400">
        <svg class="w-16 h-16 mx-auto mb-4 opacity-50" fill="none" stroke="currentColor" viewBox="0 0 24 24">
          <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M8 7H5a2 2 0 00-2 2v9a2 2 0 002 2h14a2 2 0 002-2V9a2 2 0 00-2-2h-3m-1 4l-3 3m0 0l-3-3m3 3V4" />
        </svg>
        <p class="text-sm">No story loaded</p>
      </div>
    {:else if viewMode === 'config'}
      <!-- Configuration -->
      <div class="space-y-4">
        <!-- Storage Type -->
        <div>
          <div class="text-sm font-medium text-gray-900 dark:text-gray-100 mb-2">
            Storage Type
          </div>
          <select
            bind:value={$storageType}
            onchange={(e) => saveSystemStore.setStorageType(e.currentTarget.value as SaveStorageType)}
            class="w-full px-3 py-2 border border-gray-300 dark:border-gray-600 rounded bg-white dark:bg-gray-700 text-gray-900 dark:text-gray-100 text-sm"
          >
            <option value="localStorage">localStorage (Browser)</option>
            <option value="indexedDB">IndexedDB (Browser, large data)</option>
            <option value="json">JSON File (Download)</option>
            <option value="custom">Custom (Manual implementation)</option>
          </select>
          <p class="text-xs text-gray-500 dark:text-gray-400 mt-1">
            {#if $storageType === 'localStorage'}
              Stores saves in browser localStorage (5-10MB limit)
            {:else if $storageType === 'indexedDB'}
              Stores saves in IndexedDB (larger capacity, async)
            {:else if $storageType === 'json'}
              Downloads saves as JSON files (manual load required)
            {:else}
              Generates code structure for custom implementation
            {/if}
          </p>
        </div>

        <!-- Save Slots -->
        <div>
          <div class="text-sm font-medium text-gray-900 dark:text-gray-100 mb-2">
            Save Slots
          </div>
          <div class="space-y-2">
            {#each $slots as slot}
              <div class="p-3 border border-gray-200 dark:border-gray-700 rounded">
                <div class="flex items-center justify-between mb-2">
                  <label class="flex items-center gap-2">
                    <input
                      type="checkbox"
                      checked={slot.enabled}
                      onchange={(e) => saveSystemStore.updateSlot(slot.type, { enabled: e.currentTarget.checked })}
                      class="rounded"
                    />
                    <span class="text-sm font-medium text-gray-900 dark:text-gray-100">
                      {slot.type === 'manual' ? '💾' : slot.type === 'auto' ? '⚡' : '⚡'}
                      {slot.label}
                    </span>
                  </label>
                </div>
                {#if slot.enabled}
                  <div class="flex items-center gap-2">
                    <span class="text-xs text-gray-600 dark:text-gray-400">Count:</span>
                    <input
                      type="number"
                      min="1"
                      max="10"
                      value={slot.count}
                      onchange={(e) => saveSystemStore.updateSlot(slot.type, { count: parseInt(e.currentTarget.value) })}
                      class="w-16 px-2 py-1 border border-gray-300 dark:border-gray-600 rounded bg-white dark:bg-gray-700 text-gray-900 dark:text-gray-100 text-sm"
                    />
                  </div>
                {/if}
              </div>
            {/each}
          </div>
        </div>

        <!-- Metadata -->
        <div>
          <div class="text-sm font-medium text-gray-900 dark:text-gray-100 mb-2">
            Save Metadata
          </div>
          <div class="space-y-1">
            <label class="flex items-center gap-2 text-sm text-gray-700 dark:text-gray-300">
              <input
                type="checkbox"
                checked={$metadata.includeTimestamp}
                onchange={(e) => saveSystemStore.updateMetadata({ includeTimestamp: e.currentTarget.checked })}
                class="rounded"
              />
              Include timestamp
            </label>
            <label class="flex items-center gap-2 text-sm text-gray-700 dark:text-gray-300">
              <input
                type="checkbox"
                checked={$metadata.includePlaytime}
                onchange={(e) => saveSystemStore.updateMetadata({ includePlaytime: e.currentTarget.checked })}
                class="rounded"
              />
              Include playtime
            </label>
            <label class="flex items-center gap-2 text-sm text-gray-700 dark:text-gray-300">
              <input
                type="checkbox"
                checked={$metadata.includePassageTitle}
                onchange={(e) => saveSystemStore.updateMetadata({ includePassageTitle: e.currentTarget.checked })}
                class="rounded"
              />
              Include current passage
            </label>
            <label class="flex items-center gap-2 text-sm text-gray-700 dark:text-gray-300">
              <input
                type="checkbox"
                checked={$metadata.includeStoryProgress}
                onchange={(e) => saveSystemStore.updateMetadata({ includeStoryProgress: e.currentTarget.checked })}
                class="rounded"
              />
              Include progress percentage
            </label>
            <label class="flex items-center gap-2 text-sm text-gray-700 dark:text-gray-300">
              <input
                type="checkbox"
                checked={$metadata.includeScreenshot}
                onchange={(e) => saveSystemStore.updateMetadata({ includeScreenshot: e.currentTarget.checked })}
                class="rounded"
              />
              Include screenshot (experimental)
            </label>
          </div>
        </div>

        <!-- Custom Fields -->
        <div>
          <div class="text-sm font-medium text-gray-900 dark:text-gray-100 mb-2">
            Custom Metadata Fields
          </div>
          {#if $metadata.customFields.length > 0}
            <div class="space-y-1 mb-2">
              {#each $metadata.customFields as field}
                <div class="flex items-center justify-between p-2 bg-gray-50 dark:bg-gray-900 rounded">
                  <div class="text-sm text-gray-900 dark:text-gray-100">
                    <span class="font-medium">{field.label}</span>
                    <span class="text-xs text-gray-500">({field.type})</span>
                  </div>
                  <button
                    onclick={() => saveSystemStore.removeCustomField(field.key)}
                    class="text-red-600 hover:text-red-700 text-xs"
                  >
                    Remove
                  </button>
                </div>
              {/each}
            </div>
          {/if}
          <div class="flex gap-2">
            <input
              type="text"
              bind:value={customFieldKey}
              placeholder="Field key (e.g., difficulty)"
              class="flex-1 px-2 py-1 border border-gray-300 dark:border-gray-600 rounded bg-white dark:bg-gray-700 text-gray-900 dark:text-gray-100 text-xs"
            />
            <input
              type="text"
              bind:value={customFieldLabel}
              placeholder="Label"
              class="flex-1 px-2 py-1 border border-gray-300 dark:border-gray-600 rounded bg-white dark:bg-gray-700 text-gray-900 dark:text-gray-100 text-xs"
            />
            <select
              bind:value={customFieldType}
              class="px-2 py-1 border border-gray-300 dark:border-gray-600 rounded bg-white dark:bg-gray-700 text-gray-900 dark:text-gray-100 text-xs"
            >
              <option value="string">string</option>
              <option value="number">number</option>
              <option value="boolean">boolean</option>
            </select>
            <button
              onclick={addCustomField}
              disabled={!customFieldKey || !customFieldLabel}
              class="px-2 py-1 bg-green-600 hover:bg-green-700 disabled:bg-gray-400 text-white rounded text-xs"
            >
              Add
            </button>
          </div>
        </div>

        <!-- Advanced Options -->
        <div>
          <div class="text-sm font-medium text-gray-900 dark:text-gray-100 mb-2">
            Advanced Options
          </div>
          <div class="space-y-2">
            <label class="flex items-center gap-2 text-sm text-gray-700 dark:text-gray-300">
              <input
                type="checkbox"
                checked={$persistAll}
                onchange={() => saveSystemStore.togglePersistAll()}
                class="rounded"
              />
              Save all variables (uncheck to select specific ones)
            </label>
          </div>
        </div>
      </div>
    {:else if viewMode === 'variables'}
      <!-- Variables Selection -->
      <div class="space-y-3">
        <div class="text-sm text-gray-600 dark:text-gray-400">
          {#if $persistAll}
            Select variables to <strong>exclude</strong> from saves:
          {:else}
            Select variables to <strong>include</strong> in saves:
          {/if}
        </div>

        {#if $currentStory.variables.size === 0}
          <div class="text-center py-8 text-gray-500 dark:text-gray-400">
            <p class="text-sm">No variables defined in story</p>
          </div>
        {:else}
          <div class="space-y-1">
            {#each $currentStory.variables as [, variable]}
              <label class="flex items-center gap-2 p-2 hover:bg-gray-50 dark:hover:bg-gray-900 rounded">
                <input
                  type="checkbox"
                  checked={$persistAll ? excludedVariables.includes(variable.name) : selectedVariables.includes(variable.name)}
                  onchange={(e) => {
                    if ($persistAll) {
                      if (e.currentTarget.checked) {
                        excludedVariables = [...excludedVariables, variable.name];
                      } else {
                        excludedVariables = excludedVariables.filter(v => v !== variable.name);
                      }
                    } else {
                      if (e.currentTarget.checked) {
                        selectedVariables = [...selectedVariables, variable.name];
                      } else {
                        selectedVariables = selectedVariables.filter(v => v !== variable.name);
                      }
                    }
                  }}
                  class="rounded"
                />
                <div class="flex-1">
                  <div class="text-sm font-medium text-gray-900 dark:text-gray-100">
                    {variable.name}
                  </div>
                  <div class="text-xs text-gray-500 dark:text-gray-400">
                    {variable.type}
                  </div>
                </div>
              </label>
            {/each}
          </div>
        {/if}
      </div>
    {:else if viewMode === 'code' && generatedCode}
      <!-- Generated Code -->
      <div class="space-y-3">
        <div class="flex items-center justify-between">
          <div class="text-sm font-medium text-gray-900 dark:text-gray-100">
            Generated Save System Code
          </div>
          <button
            onclick={downloadCode}
            class="px-3 py-1 bg-green-600 hover:bg-green-700 text-white rounded text-sm font-medium"
          >
            📥 Download All
          </button>
        </div>

        <!-- Types -->
        <div class="border border-gray-200 dark:border-gray-700 rounded">
          <div class="flex items-center justify-between p-2 bg-gray-50 dark:bg-gray-900 border-b border-gray-200 dark:border-gray-700">
            <div class="text-sm font-medium text-gray-900 dark:text-gray-100">TypeScript Types</div>
            <button
              onclick={() => copyCode('types', generatedCode.types)}
              class="text-xs text-blue-600 hover:text-blue-700 dark:text-blue-400"
            >
              {copiedSection === 'types' ? '✓ Copied!' : '📋 Copy'}
            </button>
          </div>
          <pre class="p-3 text-xs overflow-x-auto bg-white dark:bg-gray-800 text-gray-900 dark:text-gray-100"><code>{generatedCode.types}</code></pre>
        </div>

        <!-- Save Function -->
        <div class="border border-gray-200 dark:border-gray-700 rounded">
          <div class="flex items-center justify-between p-2 bg-gray-50 dark:bg-gray-900 border-b border-gray-200 dark:border-gray-700">
            <div class="text-sm font-medium text-gray-900 dark:text-gray-100">Save Function</div>
            <button
              onclick={() => copyCode('save', generatedCode.saveFunction)}
              class="text-xs text-blue-600 hover:text-blue-700 dark:text-blue-400"
            >
              {copiedSection === 'save' ? '✓ Copied!' : '📋 Copy'}
            </button>
          </div>
          <pre class="p-3 text-xs overflow-x-auto bg-white dark:bg-gray-800 text-gray-900 dark:text-gray-100"><code>{generatedCode.saveFunction}</code></pre>
        </div>

        <!-- Load Function -->
        <div class="border border-gray-200 dark:border-gray-700 rounded">
          <div class="flex items-center justify-between p-2 bg-gray-50 dark:bg-gray-900 border-b border-gray-200 dark:border-gray-700">
            <div class="text-sm font-medium text-gray-900 dark:text-gray-100">Load Function</div>
            <button
              onclick={() => copyCode('load', generatedCode.loadFunction)}
              class="text-xs text-blue-600 hover:text-blue-700 dark:text-blue-400"
            >
              {copiedSection === 'load' ? '✓ Copied!' : '📋 Copy'}
            </button>
          </div>
          <pre class="p-3 text-xs overflow-x-auto bg-white dark:bg-gray-800 text-gray-900 dark:text-gray-100"><code>{generatedCode.loadFunction}</code></pre>
        </div>

        <!-- Delete Function -->
        <div class="border border-gray-200 dark:border-gray-700 rounded">
          <div class="flex items-center justify-between p-2 bg-gray-50 dark:bg-gray-900 border-b border-gray-200 dark:border-gray-700">
            <div class="text-sm font-medium text-gray-900 dark:text-gray-100">Delete Function</div>
            <button
              onclick={() => copyCode('delete', generatedCode.deleteFunction)}
              class="text-xs text-blue-600 hover:text-blue-700 dark:text-blue-400"
            >
              {copiedSection === 'delete' ? '✓ Copied!' : '📋 Copy'}
            </button>
          </div>
          <pre class="p-3 text-xs overflow-x-auto bg-white dark:bg-gray-800 text-gray-900 dark:text-gray-100"><code>{generatedCode.deleteFunction}</code></pre>
        </div>

        <!-- List Function -->
        <div class="border border-gray-200 dark:border-gray-700 rounded">
          <div class="flex items-center justify-between p-2 bg-gray-50 dark:bg-gray-900 border-b border-gray-200 dark:border-gray-700">
            <div class="text-sm font-medium text-gray-900 dark:text-gray-100">List Function</div>
            <button
              onclick={() => copyCode('list', generatedCode.listFunction)}
              class="text-xs text-blue-600 hover:text-blue-700 dark:text-blue-400"
            >
              {copiedSection === 'list' ? '✓ Copied!' : '📋 Copy'}
            </button>
          </div>
          <pre class="p-3 text-xs overflow-x-auto bg-white dark:bg-gray-800 text-gray-900 dark:text-gray-100"><code>{generatedCode.listFunction}</code></pre>
        </div>

        <!-- Utilities -->
        {#if generatedCode.utilities.trim()}
          <div class="border border-gray-200 dark:border-gray-700 rounded">
            <div class="flex items-center justify-between p-2 bg-gray-50 dark:bg-gray-900 border-b border-gray-200 dark:border-gray-700">
              <div class="text-sm font-medium text-gray-900 dark:text-gray-100">Utility Functions</div>
              <button
                onclick={() => copyCode('utilities', generatedCode.utilities)}
                class="text-xs text-blue-600 hover:text-blue-700 dark:text-blue-400"
              >
                {copiedSection === 'utilities' ? '✓ Copied!' : '📋 Copy'}
              </button>
            </div>
            <pre class="p-3 text-xs overflow-x-auto bg-white dark:bg-gray-800 text-gray-900 dark:text-gray-100"><code>{generatedCode.utilities}</code></pre>
          </div>
        {/if}
      </div>
    {/if}
  </div>
</div>
